---
title: "Do Women Politicians Face More Interruptions? An Exploratory Analysis of Interjections in the Australian Parliamentary Debates (2012-2025)"
abstract: "While interruptions are a natural component of parliamentary debate, they also reveal information about politicians' behaviour and power dynamics within political institutions. In this paper, we use a comprehensive dataset of digitized Australian Hansard transcripts from 2012 to 2025 to examine the content and nature of interruptions in parliamentary proceedings, with a focus on gender. Our exploratory analysis shows differences in the frequency of interruptions made towards men and women politicians, and how that has changed over time. We replicate components of this analysis with Large Language Models (LLMs) to assess the alignment between automated and manual analytical findings, and to highlight the potential of LLMs as tools in quantitative political science research. This study contributes new empirical evidence to the study of gender and legislative speech, demonstrating the value of computational methods for uncovering how subtle forms of discursive inequality reinforce power dynamics."
format: pdf
editor: visual
bibliography: ref.bib
csl: chicago.csl
---

# Introduction

Women are increasingly being elected to parliaments around the world, including in Australia. Despite gains in numerical representation, women remain underrepresented in a substantive sense, because their ability to influence political debates and shape policy outcomes is often constrained. @pitkin1967 distinguishes between these two forms of representation as *descriptive* and *substantive*. Descriptive representation refers to the presence of women in elected office, while substantive representation involves speaking and acting on behalf of women’s interests, including introducing legislation, engaging in debates, or undertaking advocacy efforts [@mccallion2024].

However, increases in women's descriptive representation do not automatically lead to stronger substantive representation. Feminist institutionalist scholars argue that political institutions are gendered in ways that constrain women’s political influence [@tremblay2003; @sawer2012; @kenny2014]. Formal and informal rules, norms, and hierarchies within institutions can subtly, yet powerfully limit women’s ability to engage in substantive representation. One such behaviour is the use of interruptions during parliamentary proceedings. Interruptions are defined as "intrusions into the current speaker's turn" [@kollock1985, p. 38]. Although interruptions are a routine and institutionally sanctioned feature of parliamentary debate, they can be employed particularly by male politicians to assert dominance, undermine, or silence female politicians [@vallejo2022]. As @och2020 argues, such interruptions can be a form of resistance to women’s substantive representation, reinforcing gendered power dynamics within parliament. 

Following Celis et al.'s [-@celis2008, p.99] calls to rethink substantive representation along the lines of "where, how, and why" does it occur, this paper emphasizes the "who" and "how." Specifically, we examine who is interrupted, focusing on the gender and political party affiliation of the Members of Parliament (MPs) and how interruptions operate as a gendered constraint on substantive representation in the Australian House of Representatives. Our paper asks: do women MPs get interrupted more than men MPs? Does political party affiliation shape which MPs get interrupted the most? How does the issue being discussed impact the likelihood or nature of interruptions?

To answer these questions, we analyze a comprehensive dataset of digitized Hansard transcripts from the 39th to 47th parliaments (November 1998 to March 2025) [@katz2025]. Through quantitative analysis of parliamentary debates and Question Time (QT), we examine the frequency and nature of interruptions along gendered, party, and policy issue lines. Our findings reveal that women MPs from centre and centre-left leaning political parties are interrupted more frequently than men MPs, especially when speaking on issues related to women.

This paper contributes to a small, but growing body of quantitative research analyzing the substantive representation of women in Australian politics [@vacaflores2025; @vandijk2025]. By combining feminist institutional analysis with quantitative methods, we reveal how institutional constraints like interruptions undermine women's substantive representation.

This paper proceeds as follows. We begin by outlining our theoretical frameworks, including women’s substantive representation, feminist institutionalism, and gendered parliamentary discourse. We then discuss our data and methodology, followed by analysis of our results. Lastly, we conclude by summarizing our main findings, highlighting our contributions, and suggesting areas for future research.

# Literature Review

## Substantive Representation

Substantive representation can be conceived as how elected representatives’ actions align with the needs and wishes of their constituents [@pitkin1967]. Women politicians are often considered to be best positioned to represent the interests and needs of women, by raising policy issues of importance to women and/or by bringing women’s perspectives to policy issues often considered more masculine, such as the economy. @krook2012 define and categorize the gendered nature of cabinet positions, suggesting that policy issues such as healthcare, social welfare, and gender equality are “women’s issues,” while more masculine-coded policy issues include the economy, defence, and foreign affairs. Neutral issues could include the environment, public works, and the civil service [@krook2012]. These categorizations are useful for understanding substantive representation, but remain contested, given different parliamentary contexts and as understanding of gender moves beyond a binary framework.

Substantive representation in practice can take a number of forms in parliamentary contexts, including introducing legislation, engaging in debates, asking questions during QT, participating in committee meetings, or undertaking advocacy efforts [@mccallion2024; @childs2009]. However, routine parliamentary rules and procedures, such as interruptions and adversarial behaviour, can be mobilized to either contribute to or undermine women’s substantive representation [@vallejo2022]. For example, @vacaflores2025 focuses on studying private members’ bills in the Australian House of Representatives, where party discipline is less likely to permeate the nature of issues raised. They find that gender and legislators’ individual backgrounds inform the types of issues addressed. In parliamentary speeches on bills, women politicians are more likely to speak to bills explicitly related to women’s issues [@hargrave2021; @back2019], or provide a gendered lens even if the legislation does not specifically address issues traditionally characterized as “women’s issues” [@rayment2024; @vacaflores2025]. 

Defining “women’s issues” remains a key concern to scholars studying substantive representation. “Women’s issues” have never been fixed or universally agreed upon, especially as contemporary understandings of gender move beyond a binary framework. @vacaflores2025 suggests a solution to this by viewing policy issues along a spectrum of “feminized” and "masculinized" issues. This approach allows for a more flexible understanding of what counts as  “women’s issues” and who can represent women. Men politicians can also undertake the substantive representation of women [@mccallion2024] and issues not traditionally characterized as “women’s issue” still hold gendered implications [@bird2005]. Nevertheless, issues such as gender-based violence, childcare, healthcare, social welfare, and education continue to be widely viewed as “women's issues” [@rayment2024; @krook2012]. 

Who raises these issues, and how they are framed in parliamentary speeches, is shaped by political affiliation, ideology, and party discipline [@rayment2024; @och2020; @tremblay2003]. In the Canadian parliament, @rayment2024 illustrates that Conservative women MPs are more likely than Liberal and New Democratic Party (NDP) MPs to speak about “women’s issues” between 1968 and 2015. However, Conservative MPs often focus on these issues through a traditional values lens, while Liberal and NDP MPs discuss these issues from a pro-gender equality perspective. This highlights that speaking and acting for women as part of substantive representation cannot be thought of in monolithic terms - party affiliation, ideology, and gender intersect, shaping how substantive representation occurs. @och2020 illustrates that in the German Bundestag, men MPs from right-leaning political parties were more likely to interrupt women MPs from centre and centre-left political parties regardless of the policy issues being discussed. This behaviour acts as a form of backlash to both their numerical presence and substantive contributions in parliament.

In Australia, scholars have documented that progressive parties such as the Australian Labor Party (ALP) and the Greens have more consistently supported gender equity measures and addressed “women’s issues,” compared to right-leaning parties such as the Liberal Party of Australia [@vacaflores2025]. However, women politicians have also worked across party lines to advance “women’s issues,” such as the successful effort to lift the ministerial veto on the importation of the abortion pill RU486 [@sawer2012]. This example demonstrates that while party affiliation and ideology can shape how substantive representation occurs, gender can, at times, exert stronger influence. Responses to legislation on domestic violence, paid parental leave, and the gender pay gap further reveal how different parties and MPs conceptualize and engage with “women’s issues.” This engagement, however, does not take place in isolation, as broader institutional norms and rules shape how MPs can speak and act on behalf of women’s interests. These cultural and institutional conditions will be discussed further in the following section.

## Parliamentary Culture and Gender

Parliamentary culture and broader institutional norms play a critical role in shaping the conditions under which women MPs can speak and act on behalf of women’s interests, despite being framed as “neutral” institutions [@collier2018]. This culture reflects and reproduces social hierarchies and power imbalances, rooted in gender, which intersect with race, sexuality, and class to shape political outcomes [@chappell2013]. In Westminster parliaments, including the Australian  House of Representatives, parliamentary culture has historically been shaped by masculine norms and values, while constraining marginalized voices [@mackay2010; @crawford2011]. Julia Gillard’s 2012 sexism and misogyny speech drew global attention to these dynamics, highlighting how women politicians face a double blind as they “...negotiate the demand to demonstrate masculine leadership attributes without tarnishing the feminine qualities expected of them [@wright2014, p. 455; @sawer2013]. Underpinning parliamentary behaviour and interactions, this culture shapes legislative debates, including interruptions, which can serve to reinforce gendered hierarchies and further marginalize women MPs. Understanding these gendered dimensions of parliamentary culture is important for understanding how interruptions can constrain women’s substantive representation.

Feminist institutionalism provides a valuable framework for analyzing gendered dynamics within parliamentary settings, drawing attention to the interaction between formal rules such as the Standing Orders and parliamentary privilege and informal rules and cultural norms [@kenny2014; @chappell2013; @mackay2010]. While formal parliamentary rules are designed to guarantee equality, informal norms often shape behaviours differently. For example, Standing Orders are intended to give women and men politicians equal speaking time, but in practice, men are more likely to interrupt women politicians. Consequently, women politicians may plan to give shorter speeches out of concern of being interrupted or abandon giving their speech entirely after being interrupted multiple times [@vallejo2022]. @hames2025 highlights that certain forms of unparliamentary language are enshrined in the Standing Orders, while other language around discussions of social issues like racism rely on case-by-case rulings by Speakers. This ambiguity and lack of codified rules could further undermine women and racialized politicians attempting to speak on behalf of marginalized groups. Furthermore, mechanisms like parliamentary privilege, which protect MPs from the legal consequences of free speech in the chamber, can help them avoid accountability on incivility and harassment, which disproportionately affect women MPs [@collier2018; @sawer2013]. Feminist institutionalism therefore directs attention toward the “hidden” ways in which gender continues to shape participation, authority, and legitimacy within political institutions [@chappell2013].

## Interruptions and Gender

Prior studies analyzing the gendered nature of interruptions in parliamentary debates and committee meetings globally show mixed results. In the German Bundestag, @och2020 found that women MPs are more likely to be interrupted than men, but argue that these interruptions are not a form of semiotic violence against women in politics (VAWIP). Similarly, @stopfner2018 employed qualitative case studies to understand whether gendered heckling is shaped by specific parliamentary contexts or reflects broader parliamentary culture. She concludes that both institutional norms and transnational parliamentary cultures contribute to the gendered interruptions that undermine women’s process-oriented substantive representation [@rayment2024]. 

In contrast, evidence from the Ecuadorian Congress presents a more nuanced picture. @vallejo2022 found that while women Members of Congress (MCs) were less likely to be interrupted than men, interruptions silenced women at a higher rate. However, they found that higher status and promotion to more prominent legislative roles could reverse some of the most negative effects of interruptions for women MCs. 

In the Canadian House of Commons, @whyte2017 found that gendered interruptions sharply increased during the 1990s, coinciding with an increase in the descriptive representation of women. Yet, @vandijk2025’s analysis of parliamentary speeches in the UK, Australia, and Croatia finds no gender difference in whether individual politicians get interrupted and that all politicians are less likely to be interrupted when more women participate in debates. Notably, they find that in Australia, the number of interruptions declined as the number of women serving in parliament increased.

Research focused on committee meetings further illustrates the gendered nature of interruptions. In the Australian Senate Estimate hearings between 2006 and 2015, @richards2016 finds that male senators used interruptions to block other speakers or assert control over the floor, with women senators and witnesses receiving the most negative interruptions. Likewise, in US state legislatures, @kathlene1994 shows that as the number of women increases in committee hearings, male legislators responded with more interruptions and verbal aggression aimed at undermining women’s substantive participation in the policymaking process. Additionally, Miller and Sutherland found that women senators faced twice as many interruptions from male colleagues when speaking about “women’s issues,” with male senators employing an aggressive form of interruptions called “rapid-fire ‘interruption clusters’” to undermine and disrupt their speeches [-@miller2023, p. 103].

Taken together, these studies of both parliamentary debates and committee meetings emphasize that even as the number of women elected increases, women politicians are often interrupted more frequently by male colleagues. This pattern largely holds across nations and institutional contexts, highlighting that interruptions undermine women politicians’ abilities to speak and act on behalf of women. By focusing on interruptions in the Australian House of Representatives from 1998 to 2025, our paper contributes to the literature by combining feminist institutionalism with quantitative methods to examine how interruptions function as a persistent, gendered constraint on women’s substantive representation in parliament.  

# Data and Methods

We use longitudinal data to identify patterns over time, particularly as the descriptive representation of women in the House of Representatives increased from 22 percent in 1998 to 44.5 percent in 2022 [@ABS2025]. This period also includes important political milestones, such as Julia Gillard’s tenure as Australia’s first woman Prime Minister (2010 to 2013), including her 2012 sexism and misogyny speech, which drew attention to the gendered nature of Australian politics [@sawer2013].

# Analysis and Results

# Conclusion

# References
